import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hita Frontend",
  description: "A new Next.js project generated by DevForge.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistMono.variable} antialiased`}
      suppressHydrationWarning
    >
      {/* No height:100% chain here — percentage heights on html/body stop
          `position: sticky` descendants from having any range to stick in. */}
      <body className="flex min-h-screen flex-col">{children}</body>
    </html>
  );
}
