import type { Metadata } from "next";
import { Geist_Mono, Lato } from "next/font/google";
import "./globals.css";

// Lato is the app-wide default so portalled UI (popovers, tooltips, toasts,
// sheets) inherits it — those render into <body>, outside any section layout.
// The landing section overrides --font-sans with Josefin Sans locally.
const lato = Lato({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hita Frontend",
  description: "A new Next.js project generated by DevForge.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lato.variable} ${geistMono.variable} font-sans antialiased`}
      suppressHydrationWarning
    >
      {/* No height:100% chain here — percentage heights on html/body stop
          `position: sticky` descendants from having any range to stick in. */}
      <body className="flex min-h-screen flex-col">{children}</body>
    </html>
  );
}
